package com.uliga.app.utils

object TestTags {

    const val INVITATION = "INVITATION"

    const val KAKAO_LOGIN_BUTTON = "KAKAO_LOGIN_BUTTON"

    const val GOOGLE_LOGIN_BUTTON = "GOOGLE_LOGIN_BUTTON"

    /**
     * HomeScreen
     */

    const val MONTH_BUDGET_VALUE = "MONTH_BUDGET_VALUE"

    const val BUDGET_SETTING = "BUDGET_SETTING"

    const val ADDING_FINANCE_SCHEDULE = "ADDING_FINANCE_SCHEDULE"

    const val TEXT_NO_EXISTED_FINANCE_SCHEDULE = "TEXT_NO_EXISTED_FINANCE_SCHEDULE"

    const val TO_MOVE_ACCOUNT_BOOK_SELECTION_ACTIVITY = "TO_MOVE_ACCOUNT_BOOK_SELECTION_ACTIVITY"

    /**
     * InvitationBottomSheet
     */

    const val NEW_INVITATION = "NEW_INVITATION"

    /**
     * BudgetSettingBottomSheet
     */


    const val BUDGET_CURRENT_DATE = "BUDGET_CURRENT_DATE"

    const val BASIC_TEXT_FIELD_BUDGET = "BASIC_TEXT_FIELD_BUDGET"

    const val BUTTON_BUDGET_SETTING = "BUTTON_BUDGET_SETTING"

    /**
     * ScheduleGenerationActivity
     */

    const val BASIC_TEXT_FIELD_NOTIFICATION_DATE = "BASIC_TEXT_FIELD_NOTIFICATION_DATE"

    const val RADIO_BUTTON_INCOME = "RADIO_BUTTON_INCOME"

    const val RADIO_BUTTON_CHARGE = "RADIO_BUTTON_CHARGE"

    const val BASIC_TEXT_FIELD_SCHEDULE = "BASIC_TEXT_FIELD_SCHEDULE"

    const val BASIC_TEXT_FIELD_COST = "BASIC_TEXT_FIELD_COST"

    const val BUTTON_ADDING_SCHEDULE = "BUTTON_ADDING_SCHEDULE"

    /**
     * FinanceScreen
     */

    const val ADDING_ACCOUNT_BOOK = "ADDING_ACCOUNT_BOOK"

    const val FINANCE_CURRENT_DATE = "FINANCE_CURRENT_DATE"

    const val FINANCE_CURRENT_MONTH = "FINANCE_CURRENT_MONTH"


    /**
     * AccountBookInputActivity
     */

    const val TRANSACTION_CURRENT_DATE = "TRANSACTION_CURRENT_DATE"

    const val DROP_DOWN_TEXT_FIELD_CATEGORY = "DROP_DOWN_TEXT_FIELD_CATEGORY"

    const val DROP_DOWN_TEXT_FIELD_PAYMENT_METHOD = "DROP_DOWN_TEXT_FIELD_PAYMENT_METHOD"

}