name: Build release APK & upload to Firebase App Distribution

on:
  push:
    branches:
      - 'develop'

jobs:
  build-release-apk-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Bump APK version
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Generate keystore
        run: |
          echo "$KEYSTORE" > keystore/keystore.b64
          base64 -d -i keystore/keystore.b64 > keystore/uliga_keystore
        env:
          KEYSTORE: ${{ secrets.APP_KEYSTORE_BASE64 }}

      - name: Build release APK
        run: ./gradlew assembleRelease