jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: gradle

            - name: Run tests
              run: ./gradlew test

            - name: Upload test report
              uses: actions/upload-artifact@v3
              with:
                  name: unit_test_report
                  path: app/build/reports/tests/testDebugUnitTest/
